[package]
name = "netflow"
version = "0.1.0"
authors = ["tkgsy <meirvg@gmail.com>"]
edition = '2018'

[dependencies]
nom = "^3.2"
byteorder = "1.2.2"
log = "0.4"
env_logger = ""
lazy_static = ""
serde = ""
serde_json = ""
serde_derive = ""