[package]
name = "netflow"
version = "0.1.0"
authors = ["tkgsy <meirvg@gmail.com>"]
edition = '2018'

[dependencies]
nom = ""
byteorder = ""
log = ""
env_logger = ""
lazy_static = ""
serde = ""
serde_json = ""
serde_derive = ""
