[package]
name = "netflow"
version = "0.2.0"
authors = ["tkgsy <meirvg@gmail.com>"]
edition = '2018'

[dependencies]
nom = "4.1.1"
byteorder = "1.2.7"
log = "0.4.6"
env_logger = "0.6.0"
lazy_static = "1.2.0"
serde = "1.0.80"
serde_json = "1.0.33"
serde_derive = "1.0.80"
failure = "0.1.3"